export default {
  compte: require('../assets/icons/compte.png'),
  favoris: require('../assets/icons/favoris.png'),
  home: require('../assets/icons/home.png'),
  orders: require('../assets/icons/orders.png'),
  search: require('../assets/icons/search.png'),
  arrow: require('../assets/icons/arrow.png'),
  close: require('../assets/icons/close.png'),
  polygon: require('../assets/icons/polygon.png'),
  star: require('../assets/icons/star.png'),
  ellipse: require('../assets/icons/ellipse.png'),
  union: require('../assets/icons/union.png'),
  menu: require('../assets/icons/menu.png'),
  logo: require('../assets/icons/logo.png'),
  shopping: require('../assets/icons/shopping.png'),
  add: require('../assets/icons/add.png'),
  export: require('../assets/icons/export.png'),
  heart: require('../assets/icons/heart.png'),
  checkout: require('../assets/icons/checkout.png'),
  negative: require('../assets/icons/negative.png'),
  plus: require('../assets/icons/plus.png'),
  stylet: require('../assets/icons/stylet.png'),
  help: require('../assets/icons/help.png'),
  logout: require('../assets/icons/logout.png'),
};
