  declare interface CategorieRequestDTO { }
  declare interface CategorieResponseDTO { }
  declare interface MessageRequestDTO { }
  declare interface MessageResponseDTO { }
  declare interface NotificationRequestDTO { }
  declare interface NotificationResponseDTO { }
  declare interface CommandeRequestDTO { }
  declare interface CommandeResponseDTO { }
  declare interface UtilisateurRequestDTO { }
  declare interface UtilisateurResponseDTO { }
  declare interface AvisRequestDTO { }
  declare interface AvisResponseDTO { }
  declare interface ContactRequestDTO { }
  declare interface ContactResponseDTO { }
  declare interface GuideRequestDTO { }
  declare interface GuideResponseDTO { }
  declare interface FavorisRequestDTO { }
  declare interface FavorisResponseDTO { }
  declare interface LangueRequestDTO { }
  declare interface LangueResponseDTO { }
  declare interface ProduitRequestDTO { }
  declare interface ProduitResponseDTO { }
  declare interface SizeRequestDTO { }
  declare interface SizeResponseDTO { }
  declare interface ColorRequestDTO { }
  declare interface ColorResponseDTO { }
  declare interface CollectionRequestDTO { }
  declare interface CollectionResponseDTO { }
  declare interface DetailRequestDTO { }
  declare interface DetailResponseDTO { }
